{% set name = "festlex-poslex" %}
{% set version = "2.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://festvox.org/packed/festival/2.5/festlex_POSLEX.tar.gz
  sha256: e7c6e3642dbd5b0d64942bc015a986fdd6244a79e51ec2e8309e63d569e49ea3

build:
  number: 0
  noarch: generic

test:
  commands:
    - test -f $PREFIX/share/festival/dicts/wsj.wp39.poslexR  # [unix]
    - test -f $PREFIX/share/festival/dicts/wsj.wp39.tri.ngrambin  # [unix]

about:
  home: https://github.com/festvox/festival
  summary: 'Part of speech lexicons and ngram from English'
  description: 'Part of speech lexicons and ngram from English'
  license: BSD-4-Clause
  license_family: BSD
  license_file: lib/dicts/COPYING.poslex
  doc_url: http://festvox.org
  dev_url: http://festvox.org

extra:
  recipe-maintainers:
    - peci1
